# Generated by Django 4.1.3 on 2022-11-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_rename_phone_num_studio_phone_number_class_duration_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guser',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='guser',
            name='user_lat',
        ),
        migrations.RemoveField(
            model_name='guser',
            name='user_long',
        ),
        migrations.AddField(
            model_name='guser',
            name='address',
            field=models.CharField(default='100 Queen St W, Toronto, ON', max_length=255),
        ),
        migrations.RemoveField(
            model_name='guser',
            name='classes',
        ),
        migrations.AddField(
            model_name='guser',
            name='classes',
            field=models.ManyToManyField(null=True, to='studios.class'),
        ),
    ]
