# Generated by Django 4.1.3 on 2022-11-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_classoccurrence_delete_time'),
        ('accounts', '0002_remove_guser_postal_code_remove_guser_user_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guser',
            name='class_occurrences',
            field=models.ManyToManyField(to='studios.classoccurrence'),
        ),
    ]
