# Generated by Django 4.1.3 on 2022-11-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0004_alter_class_coach_alter_studio_phone_number_and_more'),
        ('accounts', '0003_guser_class_occurrences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guser',
            name='classes',
            field=models.ManyToManyField(to='studios.class'),
        ),
    ]
