# Generated by Django 4.1.3 on 2022-11-19 18:43

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_guser_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='billing_end',
        ),
        migrations.AlterField(
            model_name='guser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[accounts.validators.validate_international_phonenumber]),
        ),
    ]
