# Generated by Django 4.1.3 on 2022-11-16 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_rename_phone_num_studio_phone_number_class_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(null=True)),
                ('end_datetime', models.DateTimeField(null=True)),
                ('num_attending', models.PositiveIntegerField(null=True)),
                ('parent_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studios.class')),
            ],
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
