# Generated by Django 4.1.3 on 2022-11-18 04:25

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_classoccurrence_delete_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='coach',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studio',
            name='phone_number',
            field=models.CharField(max_length=255, unique=True, validators=[accounts.validators.validate_international_phonenumber]),
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
    ]
